### PR TITLE
bugfix: add return types of methods

### PR DESCRIPTION
**Pull request by hoermannklaus**

### CODE REVIEW

**Comment by hoermannklaus** [comment]
I use TYPO3 V10.4.26 and got an "Fatal Error", because the declarations where not compatible.
https-portal-big-v2-dev-kho-t3-world-direct-at

**Comment by swilking** [comment]
the patch only works with EXT:solr 11.2.x, the versions 11.0.x and 11.1.x doesn't have a return type

**Comment by hoermannklaus** [comment]
So how can we make this work?

**Comment by swilking** [comment]
we've published an new version (2.3.7) of the extension with modified constraints. Support for EXT:solr 11.2.x will follow later.

**Comment by hoermannklaus** [comment]
Ok. Thanks

**Pull request closed without merging**
